// Generated by CoffeeScript 1.6.3
(function() {
  var child;

  child = require('child_process');

  module.exports = function(protocol, user, password, host, callback) {
    var cmd, proc;
    cmd = 'hg pull';
    if (host && protocol && user && password) {
      cmd += ' --config auth.rc.prefix=' + protocol + '://' + host + '/';
      cmd += ' --config auth.rc.username=' + user;
      cmd += ' --config auth.rc.password=' + password;
    }
    cmd += ' -u';
    return proc = child.exec(cmd, function(err, stdout, stderr) {
      if (err) {
        return callback(err);
      }
      return callback(null, stdout);
    });
  };

}).call(this);
