// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(dir) {
    var err, fail, orig;
    orig = process.cwd();
    try {
      process.chdir(dir);
    } catch (_error) {
      err = _error;
      fail = true;
    }
    process.chdir(orig);
    return !fail;
  };

}).call(this);
