// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(url) {
    var host, password, port, protocol, uri, user, _ref, _ref1, _ref2, _ref3, _ref4;
    _ref = url.split('://'), protocol = _ref[0], user = _ref[1];
    _ref1 = user.split('@'), user = _ref1[0], host = _ref1[1];
    _ref2 = user.split(':'), user = _ref2[0], password = _ref2[1];
    _ref3 = host.split('/', 2), host = _ref3[0], uri = _ref3[1];
    _ref4 = host.split(':'), host = _ref4[0], port = _ref4[1];
    protocol = protocol.toLowerCase();
    return {
      protocol: protocol,
      user: user,
      password: password,
      host: host,
      port: port,
      uri: uri
    };
  };

}).call(this);
